
spring:
  datasource:
    url: jdbc:mysql://60.205.247.46:3306/learn_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456


mybatis-plus:
? global-config:
??? db-config:
????? id-type: auto
????? field-strategy: not_empty
  ????? #�շ��»���ת��
????? column-underline: true
  ????? #�߼�ɾ������
????? logic-delete-value: 0
????? logic-not-delete-value: 1
????? db-type: mysql
??? refresh: false
? configuration:
??? map-underscore-to-camel-case: true
??? cache-enabled: false